# Generated by Django 4.0.5 on 2022-06-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=128)),
                ('level', models.CharField(max_length=128)),
                ('content', models.JSONField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
